export declare const Breakpoints: {
    XSmall: string;
    Small: string;
    Medium: string;
    Large: string;
    XLarge: string;
    Handset: string;
    Tablet: string;
    Web: string;
    HandsetPortrait: string;
    TabletPortrait: string;
    WebPortrait: string;
    HandsetLandscape: string;
    TabletLandscape: string;
    WebLandscape: string;
};
export declare const MediaQueries: {
    'xs': string;
    'sm': string;
    'md': string;
    'lg': string;
    'xl': string;
    'lt-sm': string;
    'lt-md': string;
    'lt-lg': string;
    'lt-xl': string;
    'gt-xs': string;
    'gt-sm': string;
    'gt-md': string;
    'gt-lg': string;
};
